import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Uploader from "@/components/Uploader";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Track to Text</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Upload track to convert to text</h1>
        <Uploader />
      </main>
    </>
  );
}
